# Mots classés par difficulté
# easy   : ≤ 6 lettres
# medium : 7 – 9 lettres
# hard   : 10+ lettres

WORDS = {
    "easy": [
        "maison", "jardin", "soleil", "oiseau", "nuage", "fleuve", "cheval",
        "tigre", "arbre", "plage", "matin", "nuit", "fleur", "coeur",
        "verre", "table", "chaise", "porte", "fenêtre", "lampe", "livre",
        "stylo", "gomme", "crayon", "cahier", "ecole", "route", "voiture",
        "avion", "train", "bateau", "poule", "lapin", "mouton", "canard",
        "farine", "beurre", "sucre", "huile", "lait", "pain", "gâteau",
        "orange", "citron", "fraise", "cerise", "poire", "pomme", "mangue",
        "raisin", "noix", "olive", "salade", "carotte", "oignon", "tomate",
        "sable", "rocher", "pierre", "herbe", "feuille", "racine", "tige",
        "riviere", "vallee", "colline", "foret", "desert", "ocean", "ile",
        "lune", "etoile", "vent", "pluie", "neige", "glace", "brume",
        "rouge", "bleu", "vert", "jaune", "blanc", "noir", "rose",
        "chant", "danse", "sport", "jeu", "film", "photo", "musique",
        "amour", "paix", "joie", "rire", "fete", "reve", "espoir",
    ],

    "medium": [
        "elephant", "girafe", "panthère", "dauphin", "baleine", "pintade",
        "cameleon", "perroquet", "moustique", "ecureuil", "hérisson",
        "bibliothèque", "accordeon", "calendrier", "carnaval", "champion",
        "chocolat", "chouette", "citrouille", "coccinelle", "couronne",
        "cristal", "cyclone", "detective", "diamant", "diplome",
        "domicile", "drapeau", "ecologie", "embarquer", "emission",
        "emploi", "enchanter", "energie", "enigme", "entendre",
        "escalier", "estomac", "etoile", "evasion", "exemple",
        "fabrique", "fantome", "farouche", "festival", "ficelle",
        "flamant", "flamme", "forgeron", "formule", "foudre",
        "galaxie", "gardien", "gazeuse", "girafon", "glacier",
        "glissade", "gorille", "gourmet", "grillage", "guitare",
        "hamster", "harmonie", "hirondelle", "horizon", "horloge",
        "hurricane", "hygiene", "identite", "igloo", "illusion",
        "imagine", "immeuble", "impasse", "incroyable", "indigo",
        "jongleur", "journee", "jungle", "justice", "kayak",
        "lampadaire", "lanterne", "lavandin", "legendaire", "licorne",
        "librairie", "limaces", "lingerie", "lionnes", "logiciel",
        "magicien", "magnolia", "majesté", "marathon", "marionette",
        "médaille", "menuisier", "merveille", "message", "meteore",
        "montagne", "mosquée", "nautique", "noisette", "novembre",
        "numérique", "obstacle", "olympique", "ordinateur", "organique",
        "origami", "paillasson", "palmier", "papillon", "parachute",
        "parasol", "partager", "patience", "paysage", "peinture",
        "pendule", "pétanque", "pharmacie", "physique", "pilotage",
        "pirouette", "planète", "plongeon", "poignée", "portrait",
        "poudrière", "pyramide", "question", "récolte", "rectangle",
        "réunion", "richesse", "rivière", "robotique", "romanesque",
        "rondelle", "rossignol", "royaume", "ruisseau", "sagesse",
        "saucisse", "savanne", "scorpion", "secrète", "semaine",
        "sérénité", "sifflet", "silence", "souvenir", "spectacle",
        "surprise", "symbole", "tableau", "tambour", "tendresse",
        "tournesol", "tournure", "transport", "triangle", "tropical",
        "turbulence", "univers", "vacances", "vallée", "vanille",
        "vautour", "véranda", "victoire", "vigilance", "village",
        "violette", "vitamine", "volaille", "voyage", "zèbre",
    ],

    "hard": [
        "bibliothécaire", "extraordinaire", "environnement", "accomplissement",
        "administration", "apprentissage", "archéologique", "architecture",
        "arrondissement", "astronomique", "authentification", "autobiographie",
        "bureaucratique", "caractéristique", "catastrophique", "christianisme",
        "cinématographe", "classification", "collaborateur", "communication",
        "comparaison", "compréhension", "concentration", "confidentialité",
        "connaissance", "considération", "construction", "contradiction",
        "contribution", "coopération", "correspondance", "cristallisation",
        "décentralisation", "déforestation", "démocratisation", "développement",
        "différenciation", "discrimination", "documentation", "electricité",
        "émancipation", "encombrement", "enseignement", "enthousiasme",
        "entrepreneuriat", "establishment", "expérimentation", "extraordinaire",
        "fonctionnement", "franchissement", "gouvernement", "hallucination",
        "harmonisation", "hospitalisation", "humanitaire", "identification",
        "illumination", "imagination", "implementation", "indépendance",
        "informatique", "infrastructure", "institutionnel", "interdépendance",
        "internationalisation", "interprétation", "investigation", "jurisdiction",
        "libéralisation", "magnétophone", "manifestation", "mathématiques",
        "métamorphose", "météorologie", "microbiologie", "modernisation",
        "mondialisation", "multiplication", "nationalisation", "négociation",
        "normalization", "observation", "optimisation", "organisation",
        "paléontologie", "participation", "personnalisation", "philanthropie",
        "photosynthèse", "planification", "polarisation", "popularisation",
        "préoccupation", "privatisation", "professionnalisme", "programmation",
        "prolifération", "proportionnalité", "psychologique", "radicalisation",
        "rationalisation", "réhabilitation", "représentation", "responsabilité",
        "restructuration", "rationalisation", "satisfaction", "scolarisation",
        "sensibilisation", "simplification", "socialisation", "solidarisation",
        "sophistication", "spiritualité", "standardisation", "stratification",
        "structuration", "subordination", "symbolisation", "systématisation",
        "technologique", "telecommunication", "transformation", "transparence",
        "uniformisation", "valorisation", "vérification", "vulgarisation",
    ],
}

def get_word(difficulty: str) -> str:
    import random
    return random.choice(WORDS[difficulty])
