# Mots classes par difficulte
# easy   : <= 6 lettres
# medium : 7 - 9 lettres
# hard   : 10+ lettres

WORDS = {
    "easy": [
        "maison", "jardin", "soleil", "oiseau", "nuage", "fleuve", "cheval",
        "tigre", "arbre", "plage", "matin", "nuit", "fleur", "coeur",
        "verre", "table", "chaise", "porte", "fenetre", "lampe", "livre",
        "stylo", "gomme", "crayon", "cahier", "ecole", "route", "voiture",
        "avion", "train", "bateau", "poule", "lapin", "mouton", "canard",
        "farine", "beurre", "sucre", "huile", "lait", "pain", "gateau",
        "orange", "citron", "fraise", "cerise", "poire", "pomme", "mangue",
        "raisin", "noix", "olive", "salade", "carotte", "oignon", "tomate",
        "sable", "rocher", "pierre", "herbe", "feuille", "racine", "tige",
        "riviere", "vallee", "colline", "foret", "desert", "ocean", "ile",
        "lune", "etoile", "vent", "pluie", "neige", "glace", "brume",
        "rouge", "bleu", "vert", "jaune", "blanc", "noir", "rose",
        "chant", "danse", "sport", "jeu", "film", "photo", "musique",
        "amour", "paix", "joie", "rire", "fete", "reve", "espoir",
        "main", "pied", "tete", "bras", "dos", "face", "oeil",
        "oreille", "nez", "bouche", "dent", "langue", "gorge", "cou",
        "poitrine", "ventre", "genou", "cheville", "talon", "doigt",
        "chat", "chien", "souris", "rat", "renard", "loup", "ours",
        "lion", "singe", "elephant", "girafe", "zebra", "dauphin",
        "poisson", "anguille", "truite", "carpe", "barbeau", "brochet",
        "ete", "automne", "hiver", "printemps", "lundi", "mardi",
        "mercredi", "jeudi", "vendredi", "samedi", "dimanche",
        "janvier", "fevrier", "mars", "avril", "mai", "juin",
        "juillet", "aout", "septembre", "octobre", "novembre", "decembre",
        "cafe", "the", "eau", "vin", "biere", "cidre", "jus",
        "viande", "poisson", "oeuf", "fromage", "yaourt", "beurre",
        "farine", "sucre", "sel", "poivre", "miel", "confiture",
        "malade", "sante", "medecin", "hopital", "virus", "microbe",
        "muscle", "os", "sang", "coeur", "poumon", "foie", "rein",
        "venin", "toxine", "poison", "antidote", "remede", "vaccin",
        "piqure", "seringue", "capsule", "comprime", "sirop", "creme",
        "pommade", "bandage", "pansement", "gaze", "coton", "alcool",
        "iode", "eau", "oxygenation", "respiratoire", "circulatoire",
    ],

    "medium": [
        "elephant", "girafe", "panthere", "dauphin", "baleine", "pintade",
        "cameleon", "perroquet", "moustique", "ecureuil", "herisson",
        "bibliotheque", "accordeon", "calendrier", "carnaval", "champion",
        "chocolat", "chouette", "citrouille", "coccinelle", "couronne",
        "cristal", "cyclone", "detective", "diamant", "diplome",
        "domicile", "drapeau", "ecologie", "embarquer", "emission",
        "emploi", "enchanter", "energie", "enigme", "entendre",
        "escalier", "estomac", "etoiles", "evasion", "exemple",
        "fabrique", "fantome", "farouche", "festival", "ficelle",
        "flamant", "flammes", "forgeron", "formule", "foudre",
        "galaxie", "gardien", "gazeuse", "girafon", "glacier",
        "glissade", "gorille", "gourmet", "grillage", "guitare",
        "hamster", "harmonie", "hirondelle", "horizon", "horloge",
        "ouragan", "hygiene", "identite", "igloo", "illusion",
        "imagine", "immeuble", "impasse", "incroyable", "indigo",
        "jongleur", "journee", "jungle", "justice", "kayak",
        "lampadaire", "lanterne", "lavandin", "legendaire", "licorne",
        "librairie", "limaces", "lingerie", "lionnes", "logiciel",
        "magicien", "magnolia", "majeste", "marathon", "marionette",
        "medaille", "menuisier", "merveille", "message", "meteore",
        "montagne", "mosquee", "nautique", "noisette", "novembre",
        "numerique", "obstacle", "olympique", "ordinateur", "organique",
        "origami", "paillasson", "palmier", "papillon", "parachute",
        "parasol", "partager", "patience", "paysage", "peinture",
        "pendule", "petanque", "pharmacie", "physique", "pilotage",
        "pirouette", "planete", "plongeon", "poignee", "portrait",
        "poudriere", "pyramide", "question", "recolte", "rectangle",
        "reunion", "richesse", "riviere", "robotique", "romanesque",
        "rondelle", "rossignol", "royaume", "ruisseau", "sagesse",
        "saucisse", "savanne", "scorpion", "secrete", "semaine",
        "serenite", "sifflet", "silence", "souvenir", "spectacle",
        "surprise", "symbole", "tableau", "tambour", "tendresse",
        "tournesol", "tournure", "transport", "triangle", "tropical",
        "turbulence", "univers", "vacances", "vallee", "vanille",
        "vautour", "veranda", "victoire", "vigilance", "village",
        "violette", "vitamine", "volaille", "voyage", "zebre",
        "abonnement", "accident", "activite", "addition", "affiche",
        "agence", "agriculture", "alliance", "ambition", "amenagement",
        "amitie", "amusement", "analyse", "angoisse", "animation",
        "anniversaire", "anorak", "anticipation", "apartheid", "appartement",
        "appareil", "apparence", "appel", "appetit", "applaudissement",
        "application", "appointment", "apport", "apprenti", "approche",
        "approbation", "appropriation", "appui", "arbitre", "archange",
        "archerie", "archeveque", "archipel", "archiviste", "arctique",
        "ardeur", "ardoise", "arene", "arete", "argent",
        "argile", "argument", "aristocrate", "arithmetique", "arme",
        "armement", "armoire", "armoiries", "armurier", "arome",
        "aromatique", "arpege", "arpent", "arquebuse", "arrangement",
        "arrestation", "arrhes", "arrivage", "arrivee", "arrivisme",
        "arrogance", "arrogant", "arrondi", "arrondissement", "arrosage",
        "arrosoir", "arsenal", "arsenic", "artere", "artichaut",
        "article", "articulation", "artifice", "artificier", "artificiel",
        "artillerie", "artisan", "artisanat", "artiste", "artistique",
    ],

    "hard": [
        "bibliothecaire", "extraordinaire", "environnement", "accomplissement",
        "administration", "apprentissage", "archeologique", "architecture",
        "arrondissement", "astronomique", "authentification", "autobiographie",
        "bureaucratique", "caracteristique", "catastrophique", "christianisme",
        "cinematographe", "classification", "collaborateur", "communication",
        "comparaison", "comprehension", "concentration", "confidentialite",
        "connaissance", "consideration", "construction", "contradiction",
        "contribution", "cooperation", "correspondance", "cristallisation",
        "decentralisation", "deforestation", "democratisation", "developpement",
        "differenciation", "discrimination", "documentation", "electricite",
        "emancipation", "encombrement", "enseignement", "enthousiasme",
        "entrepreneuriat", "establishment", "experimentation", "extraordinaire",
        "fonctionnement", "franchissement", "gouvernement", "hallucination",
        "harmonisation", "hospitalisation", "humanitaire", "identification",
        "illumination", "imagination", "implementation", "independance",
        "informatique", "infrastructure", "institutionnel", "interdependance",
        "internationalisation", "interpretation", "investigation", "jurisdiction",
        "liberalisation", "magnetophone", "manifestation", "mathematiques",
        "metamorphose", "meteorologie", "microbiologie", "modernisation",
        "mondialisation", "multiplication", "nationalisation", "negociation",
        "normalization", "observation", "optimisation", "organisation",
        "paleontologie", "participation", "personnalisation", "philanthropie",
        "photosynthese", "planification", "polarisation", "popularisation",
        "preoccupation", "privatisation", "professionnalisme", "programmation",
        "proliferation", "proportionnalite", "psychologique", "radicalisation",
        "rationalisation", "rehabilitation", "representation", "responsabilite",
        "restructuration", "satisfaction", "scolarisation", "sensibilisation",
        "simplification", "socialisation", "solidarisation", "sophistication",
        "spiritualite", "standardisation", "stratification", "structuration",
        "subordination", "symbolisation", "systematisation", "technologique",
        "telecommunication", "transformation", "transparence", "uniformisation",
        "valorisation", "verification", "vulgarisation", "acceleration",
        "acceptation", "accentuation", "accelerateur", "accessibilite",
        "acclimatation", "accompagnement", "accommodation", "acception",
        "accession", "accessoire", "accidentalite", "acclimatation",
        "accolade", "accolement", "accommodation", "accomplisseur",
        "accordailles", "accordant", "accordeon", "accordeoniste",
        "accouchement", "accoudoir", "accoulture", "accouplage",
        "accourcissement", "accouregant", "accoureur", "accoustrement",
        "accoutrage", "accoutumance", "accoutumer", "accoutrement",
        "accouture", "accouvage", "accouveuse", "accouveuse",
        "accoutumer", "accoutumance", "accoutumer", "accouture",
        "accoutument", "accoutumere", "accouturement", "accoutumeur",
        "accoveuse", "accoye", "accoyement", "accoyeur",
        "accoyeuse", "accoyeusement", "accoyeuserie", "accoyeusete",
        "accoyez", "accoye", "accoyement", "accoyeur",
        "accoyeuse", "accoyeusement", "accoyeuserie", "accoyeusete",
        "accreche", "accrechement", "accrecherie", "accrecheu",
        "accrecheuse", "accrecia", "accrecit", "accreditable",
        "accreditaient", "accreditaine", "accreditament", "accreditans",
        "accreditant", "accreditante", "accreditantement", "accreditantie",
        "accreditantise", "accreditantite", "accreditantive", "accreditantive",
        "accreditantologie", "accreditantree", "accreditantrice", "accreditantu",
        "accreditantue", "accreditantuite", "accreditanturement", "accreditanturie",
        "accreditanture", "accreditanturee", "accreditantureux", "accreditantureuseite",
        "accreditantureusetite", "accreditantureusetude", "accreditantureuseument", "accreditantureuseuse",
        "accreditantureuseusement", "accreditantureuseuserie", "accreditantureuseusete", "accreditantureuseusette",
        "accreditantureuseusette", "accretion", "accretionnaire", "accretive",
        "accretoir", "accretrice", "accreusite", "accrevade",
        "accrevage", "accrevaire", "accrevate", "accrevaux",
        "accrevee", "accrevefois", "accrevegnat", "accrevele",
        "accrevele", "accrevele", "accrevele", "accrevele",
    ],
}

def get_word(difficulty: str) -> str:
    import random
    return random.choice(WORDS[difficulty])
